-- Cycle improvements:
-- 1) Add postmenopause/menopause_confirmed statuses
-- 2) Add symptom logs for adaptive load
-- 3) Add deterministic exercise flags for cycle safety

-- Expand reproductive status enum-like check
ALTER TABLE IF EXISTS user_cycle_settings
DROP CONSTRAINT IF EXISTS user_cycle_settings_reproductive_status_check;

ALTER TABLE IF EXISTS user_cycle_settings
ADD CONSTRAINT user_cycle_settings_reproductive_status_check
CHECK (reproductive_status IN (
  'unspecified',
  'regular',
  'perimenopause',
  'menopause',
  'menopause_confirmed',
  'postmenopause'
));

-- Weekly/daily symptom check-ins (0..3 per symptom)
CREATE TABLE IF NOT EXISTS cycle_symptom_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chat_id text NOT NULL REFERENCES users(chat_id) ON DELETE CASCADE,
  log_date date NOT NULL DEFAULT CURRENT_DATE,
  hot_flashes smallint NOT NULL DEFAULT 0 CHECK (hot_flashes BETWEEN 0 AND 3),
  sleep_quality smallint NOT NULL DEFAULT 0 CHECK (sleep_quality BETWEEN 0 AND 3),
  fatigue smallint NOT NULL DEFAULT 0 CHECK (fatigue BETWEEN 0 AND 3),
  joint_pain smallint NOT NULL DEFAULT 0 CHECK (joint_pain BETWEEN 0 AND 3),
  mood_stress smallint CHECK (mood_stress BETWEEN 0 AND 3),
  recovery_score smallint CHECK (recovery_score BETWEEN 0 AND 3),
  note text,
  source text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_cycle_symptom_logs_chat_date
  ON cycle_symptom_logs(chat_id, log_date DESC, created_at DESC);

COMMENT ON TABLE cycle_symptom_logs IS 'Симптом-чек для адаптації навантаження у перименопаузі/постменопаузі';

-- Deterministic flags for exercise filtering by cycle phase
ALTER TABLE IF EXISTS exercise_library
ADD COLUMN IF NOT EXISTS is_inversion boolean NOT NULL DEFAULT false;

ALTER TABLE IF EXISTS exercise_library
ADD COLUMN IF NOT EXISTS is_high_impact boolean NOT NULL DEFAULT false;

COMMENT ON COLUMN exercise_library.is_inversion IS 'true: інверсії (голова нижче тазу / перевернуті пози)';
COMMENT ON COLUMN exercise_library.is_high_impact IS 'true: високоудаpні вправи (стрибки, пліометрика, ударне навантаження)';

