-- Жіночий цикл: налаштування учениці + журнал подій (місячні)

CREATE TABLE IF NOT EXISTS user_cycle_settings (
  chat_id text NOT NULL PRIMARY KEY REFERENCES users(chat_id) ON DELETE CASCADE,
  reproductive_status text NOT NULL DEFAULT 'unspecified'
    CHECK (reproductive_status IN ('unspecified', 'regular', 'perimenopause', 'menopause')),
  avg_cycle_length_days integer,
  avg_bleeding_days integer,
  last_period_start date,
  last_period_user_entered boolean NOT NULL DEFAULT false,
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT chk_cycle_len CHECK (
    avg_cycle_length_days IS NULL OR (avg_cycle_length_days >= 15 AND avg_cycle_length_days <= 60)
  ),
  CONSTRAINT chk_bleed CHECK (
    avg_bleeding_days IS NULL OR (avg_bleeding_days >= 1 AND avg_bleeding_days <= 14)
  )
);

COMMENT ON TABLE user_cycle_settings IS 'Репродуктивний статус та параметри циклу для персоналізації навантаження';
COMMENT ON COLUMN user_cycle_settings.reproductive_status IS 'regular | perimenopause | menopause | unspecified';
COMMENT ON COLUMN user_cycle_settings.last_period_user_entered IS 'Дата початку місячних введена користувачем на реєстрації / у профілі';

CREATE TABLE IF NOT EXISTS cycle_event_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chat_id text NOT NULL REFERENCES users(chat_id) ON DELETE CASCADE,
  event_type text NOT NULL CHECK (event_type IN ('period_start', 'period_end')),
  event_date date NOT NULL,
  intensity text,
  symptoms jsonb,
  source text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_cycle_event_logs_chat_date ON cycle_event_logs(chat_id, event_date DESC);

COMMENT ON TABLE cycle_event_logs IS 'Події циклу: початок/кінець місячних (ручне підтвердження та майбутні записи з бота)';
