-- ============================================
-- FIT 3.0 — таблиці для імпорту з Google Sheets
-- Виконати одним блоком у Supabase SQL Editor
-- Джерело експорту: ExportForSupabase.gs
-- ============================================

-- 1. Довідник міст (без залежностей)
CREATE TABLE IF NOT EXISTS city_list (
  city_id    text,
  city_name  text,
  PRIMARY KEY (city_id)
);

-- 2. Користувачі
CREATE TABLE IF NOT EXISTS users (
  created_at   timestamptz,
  user_id      text NOT NULL,
  chat_id      text NOT NULL UNIQUE,
  first_name   text,
  last_name    text,
  city         text,
  role         text,
  gender       text,
  age          integer,
  goal         text,
  coach_id     text,
  birth_date   timestamptz,
  height       numeric,
  weight       numeric,
  waist        numeric,
  hip          numeric,
  glutes       numeric,
  arm          numeric,
  instagram    text,
  calendar_id  text,
  experience_start_date timestamptz,
  PRIMARY KEY (chat_id)
);

-- 3. Бібліотека вправ (group_level1/2/3, name_ua, name_ru)
CREATE TABLE IF NOT EXISTS exercise_library (
  id              integer PRIMARY KEY,
  group_level1    text,
  group_level2    text,
  group_level3    text,
  name_ua         text,
  name_ru         text,
  equipment       text,
  active          text,
  focus_point     text,
  common_mistakes text,
  proper_feeling  text,
  static_holds    text,
  youtube_link    text,
  my_channel_link text,
  vid             text,  -- вид: базова, изоляция, стабилизация, растяжка
  difficulty      text   -- сложность: высокая, средняя, низкая
);

-- 4. Плани тренувань (coach_id → users)
CREATE TABLE IF NOT EXISTS training_plans (
  plan_id      text NOT NULL PRIMARY KEY,
  coach_id     text,
  plan_name    text,
  goal         text,
  level        text,
  description  text,
  is_active    text
);

-- 5. Вправи в планах (plan_id → training_plans)
CREATE TABLE IF NOT EXISTS training_plan_exercises (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plan_id        text NOT NULL,
  day            integer,
  exercise_name  text,
  sets           integer,
  reps           integer,
  rest_sec       integer,
  notes          text
);

-- 6. Ціни (coach_id, student_id → users)
CREATE TABLE IF NOT EXISTS pricing (
  id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  coach_id               text NOT NULL,
  student_id             text,
  price_personal         numeric,
  price_split            numeric,
  price_trio             numeric,
  currency               text,
  updated_at             timestamptz,
  default_training_type  text
);

-- 7. Розклад тренувань (coach_id, student_id → users)
CREATE TABLE IF NOT EXISTS workout_schedule (
  id            text NOT NULL PRIMARY KEY,
  coach_id      text NOT NULL,
  student_id    text,
  date          timestamptz,
  time          text,
  status        text,
  updated_at    timestamptz,
  cal_event_id  text,
  price_charged numeric,
  currency      text,
  training_type text,
  reschedule_from_slot_id text NULL
);

-- 8. Історія замірів (chat_id → users)
CREATE TABLE IF NOT EXISTS measurements_history (
  id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chat_id  text NOT NULL,
  date     timestamptz,
  height   numeric,
  weight   numeric,
  waist    numeric,
  hip      numeric,
  glutes   numeric,
  arm      numeric,
  source   text
);

-- 9. Записи тренувань (chat_id → users, exercise_id → exercise_library)
-- Колонка "set" в лапках: set — зарезервоване слово в PostgreSQL
CREATE TABLE IF NOT EXISTS bot_training_data (
  id_records  text NOT NULL,
  date        timestamptz,
  exercise_id integer,
  exercise    text,
  weight      numeric,
  reps        integer,
  "set"       integer,
  chat_id     text NOT NULL,
  PRIMARY KEY (id_records)
);

-- 10. Логи (опційно)
CREATE TABLE IF NOT EXISTS logs (
  id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  timestamp timestamptz,
  context   text,
  message   text,
  stack     text
);

-- Дозволи для анонімного API (якщо будете вставляти через API з anon-ключем)
ALTER TABLE city_list ENABLE ROW LEVEL SECURITY;
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE exercise_library ENABLE ROW LEVEL SECURITY;
ALTER TABLE training_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE training_plan_exercises ENABLE ROW LEVEL SECURITY;
ALTER TABLE pricing ENABLE ROW LEVEL SECURITY;
ALTER TABLE workout_schedule ENABLE ROW LEVEL SECURITY;
ALTER TABLE measurements_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE bot_training_data ENABLE ROW LEVEL SECURITY;
ALTER TABLE logs ENABLE ROW LEVEL SECURITY;

-- Політики: дозволити все для anon (для імпорту; потім можна обмежити)
CREATE POLICY "Allow all for anon" ON city_list FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for anon" ON users FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for anon" ON exercise_library FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for anon" ON training_plans FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for anon" ON training_plan_exercises FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for anon" ON pricing FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for anon" ON workout_schedule FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for anon" ON measurements_history FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for anon" ON bot_training_data FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for anon" ON logs FOR ALL USING (true) WITH CHECK (true);

-- 11. FSM State для бота (Node.js хостинг; замість PropertiesService у GAS)
CREATE TABLE IF NOT EXISTS bot_state (
  chat_id     text NOT NULL PRIMARY KEY,
  data        jsonb NOT NULL DEFAULT '{}',
  updated_at  timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE bot_state ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all for anon" ON bot_state FOR ALL USING (true) WITH CHECK (true);
