/**
 * Константи для Node.js бота FIT 3.0 (з env, без PropertiesService)
 */
const BOT_TOKEN = process.env.BOT_TOKEN || '';
const SUPABASE_URL = (process.env.SUPABASE_URL || '').replace(/\/$/, '');
const SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY || '';

const TELEGRAM_API_URL = BOT_TOKEN ? `https://api.telegram.org/bot${BOT_TOKEN}/` : '';

const CONSTANTS = Object.freeze({
  CONFIG: Object.freeze({
    BOT_TOKEN,
    TELEGRAM_API_URL,
    SUPABASE_URL,
    SUPABASE_ANON_KEY,
    DEBUG: process.env.DEBUG === '1'
  }),
  ROLES: Object.freeze({ STUDENT: 'student', COACH: 'coach' }),
  GENDERS: Object.freeze({ MALE: 'male', FEMALE: 'female' }),
  GOALS: Object.freeze({ LOSE: 'lose', GAIN: 'gain', KEEP: 'keep' }),
  FSM_STATES: Object.freeze({
    WAITING_FOR_START_CHOICE: 'WAITING_FOR_START_CHOICE',
    REG_ROLE: 'reg_role',
    REG_FIRST_NAME: 'reg_first_name',
    REG_FIRST_NAME_DECISION: 'reg_first_name_decision',
    REG_LAST_NAME: 'reg_last_name',
    REG_GENDER: 'reg_gender',
    REG_GOAL: 'reg_goal',
    REG_BIRTH_DATE: 'reg_birth_date',
    REG_CITY: 'reg_city',
    REG_INSTAGRAM: 'reg_instagram',
    REG_CALENDAR_ID: 'reg_calendar_id',
    PROFILE_WEIGHT: 'profile_weight',
    PROFILE_WAIST: 'profile_waist',
    PROFILE_HIP: 'profile_hip',
    PROFILE_GLUTES: 'profile_glutes',
    PROFILE_ARM: 'profile_arm',
    PROFILE_EDIT_FIRSTNAME: 'profile_edit_firstname',
    PROFILE_EDIT_LASTNAME: 'profile_edit_lastname',
    PROFILE_EDIT_CITY: 'profile_edit_city',
    PROFILE_EDIT_HEIGHT: 'profile_edit_height',
    PROFILE_EDIT_BIRTHDATE: 'profile_edit_birthdate',
    REG_INVITE_INPUT: 'reg_invite_input',
    COACH_ADD_STUDENT_NAME: 'coach_add_student_name',
    COACH_INVITE_INPUT: 'coach_invite_input',
    SCH_ADD_SLOT_DATE: 'sch_add_slot_date',
    SCH_ADD_SLOT_TIME: 'sch_add_slot_time',
    SCH_SELECT_STUDENT: 'sch_select_student',
    SCH_BOOK_STUDENT: 'sch_book_student',
    SCH_S_RESCHEDULE_PICK: 'sch_s_reschedule_pick',
    SCH_COACH_RESCHEDULE_PICK: 'sch_coach_reschedule_pick',
    REPORTS_TRAININGS_INPUT_DAYS: 'reports_trainings_input_days',
    REPORTS_INCOME_INPUT_DAYS: 'reports_income_input_days',
    SUB_ADD_AMOUNT: 'sub_add_amount',
    SUB_ADD_COUNT: 'sub_add_count',
    SUB_ADD_START: 'sub_add_start',
    SUB_ADD_END: 'sub_add_end',
    SCH_SETTINGS_REST_DAYS: 'sch_settings_rest_days',
    SCH_SETTINGS_DURATION: 'sch_settings_duration',
    SCH_SETTINGS_WORK_DAY: 'sch_settings_work_day',
    SCH_SETTINGS_SUMMARY: 'sch_settings_summary',
    SCH_CREATE_SLOTS_DAYS: 'sch_create_slots_days',
    SCH_ADD_SLOTS_DAY: 'sch_add_slots_day',
    PRICING_TYPE_SELECT: 'pricing_type_select',
    PRICING_INPUT_AMOUNT: 'pricing_input_amount',
    PRICING_SELECT_STUDENT: 'pricing_select_student',
    COACH_ADD_STUDENT_AGE: 'coach_add_student_age',
    COACH_ADD_STUDENT_GENDER: 'coach_add_student_gender',
    COACH_ADD_STUDENT_GOAL: 'coach_add_student_goal',
    COACH_ADD_STUDENT_EXPERIENCE: 'coach_add_student_experience',
    COACH_ADD_STUDENT_TRAINING_TYPE: 'coach_add_student_training_type',
    COACH_ADD_STUDENT_DAYS: 'coach_add_student_days',
    COACH_ADD_STUDENT_MEDICAL_CHOICE: 'coach_add_student_medical_choice',
    COACH_ADD_STUDENT_MC_CATEGORY: 'coach_add_student_mc_category',
    COACH_ADD_STUDENT_MC_SEVERITY: 'coach_add_student_mc_severity',
    COACH_ADD_STUDENT_MEASUREMENTS_CHOICE: 'coach_add_student_measurements_choice',
    COACH_ADD_STUDENT_WEIGHT: 'coach_add_student_weight',
    COACH_ADD_STUDENT_HEIGHT: 'coach_add_student_height',
    COACH_ADD_STUDENT_WAIST: 'coach_add_student_waist',
    COACH_ADD_STUDENT_GLUTES: 'coach_add_student_glutes',
    MC_ADD_CODE: 'mc_add_code',
    MC_ADD_SEVERITY: 'mc_add_severity',
    MC_ADD_SEVERITY_CUSTOM: 'mc_add_severity_custom',
    MC_PROFILE_VIEW: 'mc_profile_view',
    TRAINING_GROUP: 'training_group',
    TRAINING_EXERCISE_TYPE: 'training_exercise_type',
    TRAINING_SET_BUILD: 'training_set_build',
    TRAINING_CHOOSE_SETS: 'training_choose_sets',
    TRAINING_SET_ROUND_DONE: 'training_set_round_done',
    TRAINING_INPUT_DATA: 'training_input_data',
    TRAINING_SEARCH_NAME_INPUT: 'training_search_name_input',
    LIBRARY_BROWSE: 'library_browse',
    LIBRARY_SEARCH_INPUT: 'library_search_input',
    TRAINING_COACH_TYPE: 'training_coach_type',
    TRAINING_COACH_SELECT_STUDENTS: 'training_coach_select_students',
    TRAINING_COACH_SELECT_TARGET: 'training_coach_select_target',
    TRAINING_STUDENT_PLAN_DAY: 'training_student_plan_day',
    TRAINING_STUDENT_PLAN_INPUT: 'training_student_plan_input',
    COACH_TRAIN_PLAN_CHOICE: 'coach_train_plan_choice',
    PLAN_SET_NAME: 'plan_set_name',
    PLAN_SET_GOAL: 'plan_set_goal',
    PLAN_SET_LEVEL: 'plan_set_level',
    PLAN_SET_REVISION: 'plan_set_revision',
    PLAN_SET_DAYS: 'plan_set_days',
    PLAN_ADD_EXERCISE_DAY: 'plan_add_exercise_day',
    PLAN_ACCENT_SELECT: 'plan_accent_select',
    PLAN_AVOID_SELECT: 'plan_avoid_select',
    PLAN_SPLIT_PREVIEW: 'plan_split_preview',
    PLAN_SETS_PRESET: 'plan_sets_preset',
    PLAN_PHASE_DUR: 'plan_phase_dur',
    PLAN_PHASE_CANDIDATES: 'plan_phase_candidates',
    PLAN_PHASE_AI_WAIT: 'plan_phase_ai_wait',
    PLAN_FULL_PREVIEW: 'plan_full_preview',
    PLAN_WEEK_VIEW: 'plan_week_view',
    PLAN_WEEK_EDIT: 'plan_week_edit',
    HIST_MENU: 'hist_menu',
    HIST_SUBFILTER: 'hist_subfilter',
    HIST_GROUP_SELECT: 'hist_group_select',
    HIST_EX_SELECT: 'hist_ex_select',
    HIST_LIST: 'hist_list',
    HIST_DETAIL: 'hist_detail',
    HIST_COUNT_INPUT: 'hist_count_input',
    PLAN_SEARCH_INPUT: 'plan_search_input',
    ALIAS_INPUT_TEXT: 'alias_input_text',
    ALIAS_SELECT_SCOPE: 'alias_select_scope',
    ALIAS_CONFIRM_DELETE: 'alias_confirm_delete'
  }),
  SCHEDULE_STATUS: Object.freeze({
    AVAILABLE: 'AVAILABLE',
    RESERVED: 'RESERVED',
    REQUESTED: 'REQUESTED',
    BOOKED: 'BOOKED',
    COMPLETED: 'COMPLETED',
    CANCELED: 'CANCELED'
  }),
  INVITE: Object.freeze({
    PREFIX: 'INVITE_',
    MAX_ATTEMPTS: 5
  }),
  CALLBACKS: Object.freeze({
    REG_NEW: 'REG_NEW',
    REG_INVITE: 'REG_INVITE',
    REG_ROLE_STUDENT: 'REG_ROLE_STUDENT',
    REG_ROLE_COACH: 'REG_ROLE_COACH',
    REG_GENDER_MALE: 'REG_GENDER_MALE',
    REG_GENDER_FEMALE: 'REG_GENDER_FEMALE',
    REG_GOAL_LOSE: 'REG_GOAL_LOSE',
    REG_GOAL_GAIN: 'REG_GOAL_GAIN',
    REG_GOAL_KEEP: 'REG_GOAL_KEEP',
    REG_SKIP_LASTNAME: 'REG_SKIP_LASTNAME',
    REG_CONTINUE: 'REG_CONTINUE',
    REG_START_TRAINING: 'REG_START_TRAINING',
    BACK_TO_MAIN: 'BACK_TO_MAIN',
    CANCEL_ACTION: 'CANCEL_ACTION',
    PROFILE_VIEW: 'PROFILE_VIEW',
    PROFILE_UPDATE_MEASUREMENTS: 'PROFILE_UPDATE_MEASUREMENTS',
    PROFILE_EDIT_DATA: 'PROFILE_EDIT_DATA',
    PROFILE_EDIT_FIRSTNAME: 'PROFILE_EDIT_FIRSTNAME',
    PROFILE_EDIT_LASTNAME: 'PROFILE_EDIT_LASTNAME',
    PROFILE_EDIT_CITY: 'PROFILE_EDIT_CITY',
    PROFILE_EDIT_HEIGHT: 'PROFILE_EDIT_HEIGHT',
    PROFILE_EDIT_BIRTHDATE: 'PROFILE_EDIT_BIRTHDATE',
    BACK_TO_PROFILE: 'BACK_TO_PROFILE',
    TRAINING_START: 'TRAINING_START',
    TRAINING_COACH_START: 'TRAINING_COACH_START',
    COACH_STUDENTS: 'COACH_STUDENTS',
    COACH_ADD_STUDENT: 'COACH_ADD_STUDENT',
    COACH_ARCHIVE_MENU: 'COACH_ARCHIVE_MENU',
    COACH_BOOK: 'COACH_BOOK',
    COACH_MY_COACH_MENU: 'COACH_MY_COACH_MENU',
    COACH_INVITE_INPUT: 'COACH_INVITE_INPUT',
    COACH_PICK_START: 'COACH_PICK_START',
    PRICING_MENU: 'PRICING_MENU',
    PROFILE_PRICING: 'PROFILE_PRICING',
    PRICING_SET_DEFAULT: 'PRICING_SET_DEFAULT',
    PRICING_SET_INDIVIDUAL: 'PRICING_SET_INDIVIDUAL',
    PRICING_CHANGE: 'PRICING_CHANGE',
    PRICING_TYPE_PERSONAL: 'PRICING_TYPE_PERSONAL',
    PRICING_TYPE_SPLIT: 'PRICING_TYPE_SPLIT',
    PRICING_TYPE_TRIO: 'PRICING_TYPE_TRIO',
    SCH_MY_SCHEDULE: 'SCH_MY_SCHEDULE',
    SCH_MY_SLOTS: 'SCH_MY_SLOTS',
    SCH_CALENDAR: 'SCH_CALENDAR',
    SCH_7_ALL: 'SCH_7_ALL',
    SCH_7_AVAILABLE: 'SCH_7_AVAILABLE',
    SCH_7_BOOKED: 'SCH_7_BOOKED',
    SCH_7_REQUESTED: 'SCH_7_REQUESTED',
    SCH_7_RESERVED: 'SCH_7_RESERVED',
    SCH_7_VIEW: 'SCH_7_VIEW',
    SCH_SLOT_RESERVE: 'SCH_SLOT_RESERVE',
    SCH_SLOT_UNRESERVE: 'SCH_SLOT_UNRESERVE',
    SCH_VACATION: 'SCH_VACATION',
    SCH_VACATION_ADD: 'SCH_VACATION_ADD',
    SCH_VACATION_CALENDAR: 'SCH_VACATION_CALENDAR',
    SCH_VACATION_DAY: 'SCH_VACATION_DAY',
    SCH_VACATION_REMOVE: 'SCH_VACATION_REMOVE',
    SCH_CALENDAR_DAY: 'SCH_CALENDAR_DAY',
    SCH_BOOK_DAY: 'SCH_BOOK_DAY',
    SCH_BOOK_CALENDAR_BACK: 'SCH_BOOK_CALENDAR_BACK',
    SCH_BOOK_EXIT_STUDENTS: 'SCH_BOOK_EXIT_STUDENTS',
    SCH_BOOK_EXIT_MAIN: 'SCH_BOOK_EXIT_MAIN',
    SCH_S_BOOK_DAY: 'SCH_S_BOOK_DAY',
    SCH_S_BOOK_CALENDAR_BACK: 'SCH_S_BOOK_CALENDAR_BACK',
    SCH_DAY_VIEW: 'SCH_DAY_VIEW',
    SCH_ADD_SLOT: 'SCH_ADD_SLOT',
    SCH_CREATE_TEMPLATE: 'SCH_CREATE_TEMPLATE',
    SCH_SETTINGS_DAY: 'SCH_SETTINGS_DAY',
    SCH_SETTINGS_DAY_NONE: 'SCH_SETTINGS_DAY_NONE',
    SCH_SETTINGS_DAY_DONE: 'SCH_SETTINGS_DAY_DONE',
    SCH_SETTINGS_EDIT: 'SCH_SETTINGS_EDIT',
    SCH_SETTINGS_EDIT_REST: 'SCH_SETTINGS_EDIT_REST',
    SCH_SETTINGS_EDIT_DURATION: 'SCH_SETTINGS_EDIT_DURATION',
    SCH_SETTINGS_EDIT_WORK: 'SCH_SETTINGS_EDIT_WORK',
    SCH_SETTINGS_SAVE: 'SCH_SETTINGS_SAVE',
    SCH_CREATE_SLOTS: 'SCH_CREATE_SLOTS',
    SCH_ADD_SLOTS_FOR_DAY: 'SCH_ADD_SLOTS_FOR_DAY',
    SCH_ADD_SLOTS_DAY_PICK: 'SCH_ADD_SLOTS_DAY_PICK',
    SCH_CREATE_RESERVE: 'SCH_CREATE_RESERVE',
    SCH_STUDENT_BOOK: 'SCH_STUDENT_BOOK',
    SCH_S_MY_SCHEDULE: 'SCH_S_MY_SCHEDULE',
    SCH_S_REQ: 'SCH_S_REQ',
    SCH_C_REQ: 'SCH_C_REQ',
    SCH_CONF: 'SCH_CONF',
    SCH_DECLINE: 'SCH_DECLINE',
    SCH_CANCEL: 'SCH_CANCEL',
    SCH_COMPLETE: 'SCH_COMPLETE',
    SCH_BOOK_FOR: 'SCH_BOOK_FOR',
    SCH_S_CANCEL_REQ: 'SCH_S_CANCEL_REQ',
    SCH_S_RESCHEDULE: 'SCH_S_RESCHEDULE',
    SCH_S_RESCHEDULE_PICK: 'SCH_S_RESCHEDULE_PICK',
    SCH_S_RES_CALENDAR: 'SCH_S_RES_CALENDAR',
    SCH_S_RES_DAY: 'SCH_S_RES_DAY',
    SCH_S_RES_CANCEL: 'SCH_S_RES_CANCEL',
    SCH_S_SLOT_INFO: 'SCH_S_SLOT_INFO',
    SCH_COACH_CONF_CANCEL: 'SCH_COACH_CONF_CANCEL',
    SCH_COACH_DECLINE_CANCEL: 'SCH_COACH_DECLINE_CANCEL',
    SCH_COACH_CONF_RESCHEDULE: 'SCH_COACH_CONF_RESCHEDULE',
    SCH_COACH_DECLINE_RESCHEDULE: 'SCH_COACH_DECLINE_RESCHEDULE',
    SCH_CANCEL_REQ: 'SCH_CANCEL_REQ',
    SCH_RESCHEDULE_REQ: 'SCH_RESCHEDULE_REQ',
    SCH_RESCHEDULE_PICK: 'SCH_RESCHEDULE_PICK',
    SCH_STUDENT_CONF_CANCEL: 'SCH_STUDENT_CONF_CANCEL',
    SCH_STUDENT_DECLINE_CANCEL: 'SCH_STUDENT_DECLINE_CANCEL',
    SCH_STUDENT_CONF_RESCHEDULE: 'SCH_STUDENT_CONF_RESCHEDULE',
    SCH_STUDENT_DECLINE_RESCHEDULE: 'SCH_STUDENT_DECLINE_RESCHEDULE',
    SCH_STUDENT_CONF_COACH_BOOK: 'SCH_STUDENT_CONF_COACH_BOOK',
    SCH_STUDENT_DECLINE_COACH_BOOK: 'SCH_STUDENT_DECLINE_COACH_BOOK',
    /* Короткі форми для inline-кнопок (Telegram обмежує callback_data 64 байтами) */
    SCH_SC_CONF: 'SCH_SC_CONF',
    SCH_SC_DECL: 'SCH_SC_DECL',
    SCH_S_RES: 'SCH_S_RES',
    MENU_TRAINING: 'MENU_TRAINING',
    MENU_SCHEDULE: 'MENU_SCHEDULE',
    MENU_SUBSCRIPTION: 'MENU_SUBSCRIPTION',
    HISTORY_MENU: 'HISTORY_MENU',
    REPORTS_MENU: 'REPORTS_MENU',
    REPORTS_TRAININGS: 'REPORTS_TRAININGS',
    REPORTS_INCOME: 'REPORTS_INCOME',
    LIBRARY_VIEW: 'LIBRARY_VIEW',
    LIBRARY_GROUP: 'LIBRARY_GROUP',
    LIBRARY_EXERCISE: 'LIBRARY_EXERCISE',
    LIBRARY_SEARCH: 'LIBRARY_SEARCH',
    LIBRARY_BACK: 'LIBRARY_BACK',
    LIBRARY_TOP: 'LIBRARY_TOP',
    TRAINING_COACH_TYPE_PERSONAL: 'TRAINING_COACH_TYPE_PERSONAL',
    TRAINING_COACH_TYPE_SPLIT: 'TRAINING_COACH_TYPE_SPLIT',
    TRAINING_COACH_TYPE_TRIO: 'TRAINING_COACH_TYPE_TRIO',
    TRAINING_COACH_CHOOSE_STUDENT: 'TRAINING_COACH_CHOOSE_STUDENT',
    TRAINING_SELECT_STUDENT: 'TRAINING_SELECT_STUDENT',
    TRAINING_PICK_STUDENT: 'TRAINING_PICK_STUDENT',
    TRAINING_MODE_SINGLE: 'TRAINING_MODE_SINGLE',
    TRAINING_FINISH: 'TRAINING_FINISH',
    TRAINING_ADD_SET: 'TRAINING_ADD_SET',
    TRAINING_FINISH_EXERCISE: 'TRAINING_FINISH_EXERCISE',
    TRAINING_EXEC_TYPE_SINGLE: 'TRAINING_EXEC_TYPE_SINGLE',
    TRAINING_EXEC_TYPE_SET: 'TRAINING_EXEC_TYPE_SET',
    TRAINING_SEARCH_NAME: 'TRAINING_SEARCH_NAME',
    TRAINING_BACK_TO_GROUP: 'TRAINING_BACK_TO_GROUP',
    TRAINING_SET_ADD_MORE: 'TRAINING_SET_ADD_MORE',
    TRAINING_SET_GO: 'TRAINING_SET_GO',
    TRAINING_SET_ADD_ROUND: 'TRAINING_SET_ADD_ROUND',
    TRAINING_SET_FINISH: 'TRAINING_SET_FINISH',
    TRAINING_PLANNED_SETS: 'TRAINING_PLANNED_SETS',
    TRAINING_PLANNED_ROUNDS: 'TRAINING_PLANNED_ROUNDS',
    SUB_ADD: 'SUB_ADD',
    SUB_HISTORY: 'SUB_HISTORY',
    SUB_TYPE_UNLIMITED: 'SUB_TYPE_UNLIMITED',
    SUB_TYPE_FIXED: 'SUB_TYPE_FIXED'
  }),
  CALLBACK_PREFIXES: Object.freeze({
    INVITE_GENDER: 'INVITE_GENDER',
    INVITE_GOAL: 'INVITE_GOAL',
    INVITE_EXP: 'INVITE_EXP',
    INVITE_TYPE: 'INVITE_TYPE',
    INVITE_DAYS: 'INVITE_DAYS',
    INVITE_MC_SKIP: 'INVITE_MC_SKIP',
    INVITE_MC_FILL: 'INVITE_MC_FILL',
    INVITE_MC_DONE: 'INVITE_MC_DONE',
    INVITE_MEASUREMENTS_SKIP: 'INVITE_MEASUREMENTS_SKIP',
    INVITE_MEASUREMENTS_FILL: 'INVITE_MEASUREMENTS_FILL',
    INVITE_MC_CAT_SKIP: 'INVITE_MC_CAT_SKIP',
    INVITE_MC_CAT_OPEN: 'INVITE_MC_CAT_OPEN',
    INVITE_MC_COND: 'INVITE_MC_COND',
    INVITE_MC_SEV: 'INVITE_MC_SEV',
    INVITE_MC_CAT_BACK: 'INVITE_MC_CAT_BACK',
    COACH_PROFILE: 'COACH_PROFILE',
    CITY: 'CITY',
    VIEW_STUDENT: 'VIEW_STUDENT',
    COACH_TRAIN: 'COACH_TRAIN',
    COACH_TRAIN_FREE: 'COACH_TRAIN_FREE',
    COACH_PLAN_DAY: 'COACH_PLAN_DAY',
    COACH_HISTORY: 'COACH_HISTORY',
    COACH_BOOK: 'COACH_BOOK',
    COACH_ARCHIVE_STUDENT: 'COACH_ARCHIVE_STUDENT',
    COACH_ACTIVATE_STUDENT: 'COACH_ACTIVATE_STUDENT',
    COACH_DELETE_STUDENT: 'COACH_DELETE_STUDENT',
    VIEW_ARCHIVED_STUDENT: 'VIEW_ARCHIVED_STUDENT',
    PRICING_STUDENT: 'PRICING_STUDENT',
    STUDENT_TRAINING_TYPE: 'STUDENT_TRAINING_TYPE',
    STUDENT_TYPE_PERSONAL: 'STUDENT_TYPE_PERSONAL',
    STUDENT_TYPE_SPLIT: 'STUDENT_TYPE_SPLIT',
    STUDENT_TYPE_TRIO: 'STUDENT_TYPE_TRIO',
    STUDENT_EXPERIENCE: 'STUDENT_EXPERIENCE',
    STUDENT_EXPERIENCE_0_3: 'STUDENT_EXPERIENCE_0_3',
    STUDENT_EXPERIENCE_4_6: 'STUDENT_EXPERIENCE_4_6',
    STUDENT_EXPERIENCE_6_12: 'STUDENT_EXPERIENCE_6_12',
    STUDENT_EXPERIENCE_MORE_YEAR: 'STUDENT_EXPERIENCE_MORE_YEAR',
    STUDENT_DAYS: 'STUDENT_DAYS',
    MC_PROFILE: 'MC_PROFILE',
    MC_ADD: 'MC_ADD',
    MC_REMOVE: 'MC_REMOVE',
    MC_SEVERITY: 'MC_SEVERITY',
    MC_CATEGORY_SKIP: 'MC_CAT_SKIP',
    MC_CATEGORY_OPEN: 'MC_CAT_OPEN',
    MC_CONDITION: 'MC_COND',
    PLAN_LIST: 'PLAN_LIST',
    PLAN_NEW: 'PLAN_NEW',
    PLAN_MANUAL: 'PLAN_MANUAL',
    PLAN_AUTO: 'PLAN_AUTO',
    PLAN_AUTO_COUNT: 'PLAN_AUTO_COUNT',
    PLAN_GENERATE: 'PLAN_GENERATE',
    PLAN_GOAL: 'PLAN_GOAL',
    PLAN_LEVEL: 'PLAN_LEVEL',
    PLAN_REVISION_BACK: 'PLAN_REVISION_BACK',
    PLAN_REVISION_DEFAULT: 'PLAN_REVISION_DEFAULT',
    PLAN_REVISION_INPUT: 'PLAN_REVISION_INPUT',
    PLAN_BACK_TO_PLAN: 'PLAN_BACK_TO_PLAN',
    PLAN_VIEW_EXERCISE: 'PLAN_VIEW_EXERCISE',
    PLAN_REVISION_WEEKS: 'PLAN_REVISION_WEEKS',
    PLAN_DAYS: 'PLAN_DAYS',
    PLAN_ACTIVATE: 'PLAN_ACTIVATE',
    PLAN_DELETE: 'PLAN_DELETE',
    PLAN_DELETE_EXERCISE: 'PLAN_DEL_EX',
    PLAN_VIEW: 'PLAN_VIEW',
    PLAN_EDIT: 'PLAN_EDIT',
    PLAN_EDIT_DAY: 'PLAN_EDIT_DAY',
    PLAN_SEARCH: 'PLAN_SEARCH',
    PLAN_GROUP: 'PLAN_GROUP',
    PLAN_EXERCISE: 'PLAN_EXERCISE',
    PLAN_EXERCISE_ADD: 'PLAN_EXERCISE_ADD',
    PLAN_ACCENT_START: 'PLAN_ACC_ST',
    PLAN_ACCENT_TOGGLE: 'PLAN_ACC_TGL',
    PLAN_ACCENT_NEXT: 'PLAN_ACC_NXT',
    PLAN_ACCENT_BACK: 'PLAN_ACC_BCK',
    PLAN_AVOID_TOGGLE: 'PLAN_AVD_TGL',
    PLAN_AVOID_SKIP: 'PLAN_AVD_SKP',
    PLAN_AVOID_NEXT: 'PLAN_AVD_NXT',
    PLAN_AVOID_BACK: 'PLAN_AVD_BCK',
    PLAN_AVOID_DISABLED: 'PLAN_AVD_OFF',
    PLAN_SPLIT_CONFIRM: 'PLAN_SPL_CFM',
    PLAN_SPLIT_BACK: 'PLAN_SPL_BCK',
    PLAN_SETS_PRESET: 'PLAN_SETS_PR',
    PLAN_SETS_CUSTOM: 'PLAN_SETS_CU',
    PLAN_SETS_BACK: 'PLAN_SETS_BC',
    PLAN_PHASE_DUR: 'PLAN_PHASE_DUR',
    PLAN_CAND_REPLACE: 'PLAN_CAND_REPLACE',
    PLAN_CAND_CONFIRM: 'PLAN_CAND_CONFIRM',
    PLAN_FULL_WEEK: 'PLAN_FULL_WEEK',
    PLAN_FULL_AI_REASON: 'PLAN_FULL_AI_REASON',
    PLAN_FULL_EDIT: 'PLAN_FULL_EDIT',
    PLAN_EDIT_WEEK: 'PLAN_EDIT_WEEK',
    PLAN_ACTIVATE_PROG: 'PLAN_ACTIVATE_PROG',
    HIST_OPEN: 'HIST_OPEN',
    HIST_FILTER: 'HIST_FILTER',
    HIST_GROUP: 'HIST_GROUP',
    HIST_EX: 'HIST_EX',
    HIST_SUB: 'HIST_SUB',
    HIST_VIEW: 'HIST_VIEW',
    HIST_PREV: 'HIST_PREV',
    HIST_NEXT: 'HIST_NEXT',
    HIST_BACK_MENU: 'HIST_BACK_MENU',
    HIST_BACK_SUBFILTER: 'HIST_BACK_SUBFILTER',
    HIST_BACK_LIST: 'HIST_BACK_LIST',
    HIST_BACK_GROUP: 'HIST_BACK_GROUP',
    HIST_BACK_STUDENT: 'HIST_BACK_STUDENT',
    PLAN_DAY_DONE: 'PLAN_DAY_DONE',
    PLAN_SAVE: 'PLAN_SAVE',
    STUDENT_PLAN_DAY: 'STUDENT_PLAN_DAY',
    GROUP: 'GROUP',
    GROUP2: 'GROUP2',
    EXERCISE: 'EXERCISE',
    ALIAS_ADD: 'ALIAS_ADD',
    ALIAS_SCOPE: 'ALIAS_SCOPE',
    ALIAS_LIST: 'ALIAS_LIST',
    ALIAS_DEL: 'ALIAS_DEL',
    ALIAS_DEL_CONFIRM: 'ALIAS_DEL_CONFIRM',
    ALIAS_BACK: 'ALIAS_BACK'
  }),
  TRAINING_MODES: Object.freeze({ STUDENT: 'STUDENT', COACH: 'COACH', SELF: 'SELF' }),
  TRAINING_TYPES: Object.freeze({ PERSONAL: 'PERSONAL', SPLIT: 'SPLIT', TRIO: 'TRIO' }),
  TOP_LEVEL_GROUPS: Object.freeze(['Верх', 'Низ', 'Кор', 'Кардіо']),
  GROUPS_BY_TOP: Object.freeze({
    Верх: Object.freeze(['Спина', 'Груди', 'Плечі', 'Руки']),
    Низ: Object.freeze(['Ноги', 'Сідниці']),
    Кор: Object.freeze(['Прес']),
    Кардіо: Object.freeze([])
  }),
  MUSCLE_GROUPS: Object.freeze(['Груди', 'Спина', 'Ноги', 'Плечі', 'Руки', 'Прес', 'Кардіо']),
  VALIDATION: Object.freeze({
    NAME_MIN_LENGTH: 2,
    NAME_MAX_LENGTH: 30,
    LASTNAME_MIN_LENGTH: 2,
    LASTNAME_MAX_LENGTH: 50,
    CITY_MIN_LENGTH: 2,
    CITY_MAX_LENGTH: 50,
    AGE_MIN: 12,
    AGE_MAX: 100,
    HEIGHT_MIN: 100,
    HEIGHT_MAX: 250,
    WEIGHT_MIN: 30,
    WEIGHT_MAX: 300,
    WAIST_MIN: 40,
    WAIST_MAX: 200,
    HIP_MIN: 40,
    HIP_MAX: 200,
    GLUTES_MIN: 40,
    GLUTES_MAX: 200,
    ARM_MIN: 15,
    ARM_MAX: 80,
    PRICE_MIN: 0,
    PRICE_MAX: 999999
  }),
  PRICING: Object.freeze({
    DEFAULT_CURRENCY: 'UAH'
  }),
  DATE_FORMATS: Object.freeze({
    INPUT_PATTERN: /^\d{2}\.\d{2}\.\d{4}$/,
    EXAMPLE: '15.05.1995'
  }),
  SCHEDULE_FORMATS: Object.freeze({
    DATE_PATTERN: /^\d{2}\.\d{2}\.\d{4}$/,
    DATE_EXAMPLE: '10.02.2026',
    TIME_PATTERN: /^([01]?\d|2[0-3]):([0-5]\d)$/,
    TIME_EXAMPLE: '15:00'
  }),
  SCHEDULE_SETTINGS: Object.freeze({
    SLOTS_DAYS_MIN: 7,
    SLOTS_DAYS_MAX: 30,
    SLOTS_HORIZON_DAYS: 30,
    DURATION_MIN: 15,
    DURATION_MAX: 180,
    WORK_START_DEFAULT: '09:00',
    WORK_END_DEFAULT: '21:00',
    WEEKDAYS_UA: ['Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб', 'Нд']
  }),
  REG_PATTERNS: Object.freeze({
    INSTAGRAM_URL: /^https?:\/\/(www\.)?instagram\.com\/[^\s/]+\/?(\?.*)?$/i,
    EMAIL: /^[^\s@]+@[^\s@]+\.[^\s@]+$/
  }),
  EMOJI: Object.freeze({
    BACK: '🔙',
    HOME: '🏠',
    CANCEL: '❌',
    OK: '✅'
  }),
  /** Підписи цілей для назви прогресивного плану (План Схуднення 7 тижнів) */
  GOAL_LABELS: Object.freeze({
    lose: 'Схуднення',
    gain: 'Набір маси',
    keep: 'Підтримка'
  }),
  /** Фази прогресивного плану */
  PROGRESSIVE_PHASES: Object.freeze(['A', 'B', 'C'])
});

// ─── Акцент-зони (ТЗ_Акцент_зони_та_пресети_сетів_FIT3.md) ───────────────────

// Відповідає group_level2 з exercise_library: Спина, Груди, Плечі, Сідниці, Ноги, Прес, Руки
const ACCENT_MAP = Object.freeze({
  glutes: ['Сідниці'],
  legs: ['Ноги'],
  thighs: ['Ноги', 'Сідниці'],
  abs: ['Прес'],
  arms: ['Руки'],
  back: ['Спина'],
  shoulders: ['Плечі'],
  full: []
});

const ACCENT_LABELS = Object.freeze({
  glutes: 'Ягодиці',
  legs: 'Ноги',
  thighs: 'Стегна',
  abs: 'Прес',
  arms: 'Руки',
  back: 'Спина',
  shoulders: 'Плечі',
  full: 'Все рівномірно'
});

const ACCENT_ZONES_ORDER = Object.freeze(['glutes', 'legs', 'thighs', 'abs', 'arms', 'back', 'shoulders', 'full']);
const AVOID_ZONES_ORDER = Object.freeze(['glutes', 'legs', 'thighs', 'abs', 'arms', 'back', 'shoulders']);

const ACCENT_DAYS_COUNT = Object.freeze({ 2: 1, 3: 2, 4: 3, 5: 3 });

const SET_PRESETS = Object.freeze({
  lose: {
    beginner: [
      { label: '3 × 15', sets: 3, reps: 15, rest_sec: 60 },
      { label: '4 × 12', sets: 4, reps: 12, rest_sec: 60 },
      { label: '2 × 20', sets: 2, reps: 20, rest_sec: 45 }
    ],
    intermediate: [
      { label: '4 × 15', sets: 4, reps: 15, rest_sec: 60 },
      { label: '3 × 20', sets: 3, reps: 20, rest_sec: 45 },
      { label: '4 × 12', sets: 4, reps: 12, rest_sec: 60 }
    ],
    advanced: [
      { label: '4 × 20', sets: 4, reps: 20, rest_sec: 45 },
      { label: '5 × 15', sets: 5, reps: 15, rest_sec: 60 },
      { label: '3 × 25', sets: 3, reps: 25, rest_sec: 30 }
    ]
  },
  gain: {
    beginner: [
      { label: '3 × 8-10', sets: 3, reps: 9, rest_sec: 90 },
      { label: '4 × 6-8', sets: 4, reps: 7, rest_sec: 120 },
      { label: '3 × 10', sets: 3, reps: 10, rest_sec: 90 }
    ],
    intermediate: [
      { label: '4 × 6-8', sets: 4, reps: 7, rest_sec: 120 },
      { label: '5 × 5', sets: 5, reps: 5, rest_sec: 180 },
      { label: '3 × 8', sets: 3, reps: 8, rest_sec: 90 }
    ],
    advanced: [
      { label: '5 × 5', sets: 5, reps: 5, rest_sec: 180 },
      { label: '6 × 4-6', sets: 6, reps: 5, rest_sec: 180 },
      { label: '4 × 8', sets: 4, reps: 8, rest_sec: 120 }
    ]
  },
  keep: {
    beginner: [
      { label: '3 × 10-12', sets: 3, reps: 11, rest_sec: 75 },
      { label: '3 × 12', sets: 3, reps: 12, rest_sec: 75 },
      { label: '4 × 10', sets: 4, reps: 10, rest_sec: 75 }
    ],
    intermediate: [
      { label: '3 × 10-12', sets: 3, reps: 11, rest_sec: 75 },
      { label: '4 × 10', sets: 4, reps: 10, rest_sec: 75 },
      { label: '4 × 12', sets: 4, reps: 12, rest_sec: 60 }
    ],
    advanced: [
      { label: '4 × 10-12', sets: 4, reps: 11, rest_sec: 75 },
      { label: '5 × 8-10', sets: 5, reps: 9, rest_sec: 90 },
      { label: '3 × 12', sets: 3, reps: 12, rest_sec: 60 }
    ]
  }
});

module.exports = {
  CONSTANTS,
  BOT_TOKEN,
  SUPABASE_URL,
  SUPABASE_ANON_KEY,
  TELEGRAM_API_URL,
  ACCENT_MAP,
  ACCENT_LABELS,
  ACCENT_ZONES_ORDER,
  AVOID_ZONES_ORDER,
  ACCENT_DAYS_COUNT,
  SET_PRESETS
};
